


version: '3'

services:
  bot:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: python main.py

  redis:
    image: redis:alpine

  celery:
    build: .
    depends_on:
      - redis
    command: celery -A celery_app worker --loglevel=info

  celery_beat:
    build: .
    depends_on:
      - redis
    command: celery -A celery_app beat --loglevel=info